name = "Kitambi"
author = "Ambiguities"
version = "0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7964d7495e6e5343eaaa5899c9b3bbe31e97f6ac439c899d8987d9b56678a584"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
