name = "Kitambi"
author = "Ambiguities"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1798f0720f34129d77ea061a9af3ef3c9a4a9726a1c5da20faf6d109058dcd94"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
