name = "Kitambi"
author = "Ambiguities"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bfa0538321b2af8d3a3fac881a63c645aa5ca7af229896675be31d88b7383e6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
