name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get tag name
        id: tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache-dependency-path: |
            packwiz/go.sum
    
      - name: Install packwiz
        run: |
          go install github.com/packwiz/packwiz@latest

      - name: Package for Modrinth and CurseForge
        run: |
          packwiz modrinth export
          packwiz curseforge export

      - name: Create packwiz-installer zip
        env:
          VERSION_TAG: ${{ steps.tag.outputs.VERSION_TAG }}
        run: |
          zip -r "kitambi-$VERSION_TAG-packwiz-install.zip" index.toml pack.toml packwiz.sh mods kubejs

      - name: Prep output directory
        run: |
          mkdir -p release
          mv *.mrpack release/
          mv *.zip release/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*